name: Build .NET 10

# Dispara em push ou pull request na main
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # 1. Baixar o código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instalar o .NET 10
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      # 3. Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build do projeto
      - name: Build
        run: dotnet build --configuration Release --no-restore
